CREATE TABLE factory_expenses (
  expense_id VARCHAR(32) NOT NULL,
  expense_date DATE NOT NULL,
  category_id VARCHAR(32) NOT NULL,
  description VARCHAR(512) NULL,
  amount DECIMAL(18,2) NOT NULL,
  quantity DECIMAL(18,3) NULL,
  unit VARCHAR(64) NULL,
  unit_price DECIMAL(18,2) NULL,
  paid_to VARCHAR(255) NULL,
  payment_method ENUM('Cash','Bank Transfer','Mobile Money','Credit','Other') NOT NULL,
  reference VARCHAR(255) NULL,
  notes TEXT NULL,
  status ENUM('active','voided') NOT NULL DEFAULT 'active',
  recorded_by VARCHAR(32) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  voided_by VARCHAR(32) NULL,
  voided_at DATETIME NULL,
  void_reason TEXT NULL,
  PRIMARY KEY (expense_id),
  KEY idx_factory_expenses_date (expense_date),
  KEY idx_factory_expenses_category (category_id),
  KEY idx_factory_expenses_payment_method (payment_method),
  KEY idx_factory_expenses_status (status),
  CONSTRAINT chk_factory_expenses_amount_positive CHECK (amount > 0),
  CONSTRAINT chk_factory_expenses_quantity_positive CHECK (quantity IS NULL OR quantity > 0),
  CONSTRAINT chk_factory_expenses_unit_price_positive CHECK (unit_price IS NULL OR unit_price > 0),
  CONSTRAINT fk_factory_expenses_category FOREIGN KEY (category_id) REFERENCES factory_expense_categories (category_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_factory_expenses_recorded_by FOREIGN KEY (recorded_by) REFERENCES app_users (user_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_factory_expenses_voided_by FOREIGN KEY (voided_by) REFERENCES app_users (user_id) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
