CREATE TABLE IF NOT EXISTS agent_accountability_transfers (
  transfer_id VARCHAR(32) NOT NULL,
  operation_id VARCHAR(128) NOT NULL,
  case_id VARCHAR(32) NOT NULL,
  delivery_id VARCHAR(32) NOT NULL,
  vendor_id VARCHAR(32) NOT NULL,
  from_agent_user_id VARCHAR(32) NOT NULL,
  to_agent_user_id VARCHAR(32) NOT NULL,
  requested_amount DECIMAL(18,2) NOT NULL,
  accepted_amount DECIMAL(18,2) NULL,
  status ENUM('pending','accepted','rejected','cancelled') NOT NULL DEFAULT 'pending',
  reason TEXT NULL,
  initiated_by VARCHAR(32) NOT NULL,
  initiated_at DATETIME NOT NULL,
  decided_by VARCHAR(32) NULL,
  decided_at DATETIME NULL,
  decision_reason TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (transfer_id),
  UNIQUE KEY ux_agent_accountability_transfer_operation (operation_id),
  KEY idx_agent_accountability_transfer_case_status (case_id, status),
  KEY idx_agent_accountability_transfer_recipient_status (to_agent_user_id, status),
  KEY idx_agent_accountability_transfer_initiator_status (from_agent_user_id, status),
  CONSTRAINT fk_agent_accountability_transfer_case FOREIGN KEY (case_id) REFERENCES agent_accountability_cases (case_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_agent_accountability_transfer_delivery FOREIGN KEY (delivery_id) REFERENCES deliveries (delivery_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_agent_accountability_transfer_vendor FOREIGN KEY (vendor_id) REFERENCES vendors (vendor_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_agent_accountability_transfer_from_agent FOREIGN KEY (from_agent_user_id) REFERENCES app_users (user_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_agent_accountability_transfer_to_agent FOREIGN KEY (to_agent_user_id) REFERENCES app_users (user_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_agent_accountability_transfer_initiated_by FOREIGN KEY (initiated_by) REFERENCES app_users (user_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_agent_accountability_transfer_decided_by FOREIGN KEY (decided_by) REFERENCES app_users (user_id) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
