CREATE TABLE IF NOT EXISTS access_permissions (
  permission_key VARCHAR(128) NOT NULL,
  module VARCHAR(64) NOT NULL,
  section VARCHAR(128) NULL,
  action VARCHAR(64) NOT NULL,
  display_name VARCHAR(255) NOT NULL,
  description TEXT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (permission_key),
  KEY idx_access_permissions_module (module, active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS user_permission_overrides (
  override_id VARCHAR(40) NOT NULL,
  user_id VARCHAR(32) NOT NULL,
  permission_key VARCHAR(128) NOT NULL,
  effect ENUM('allow', 'deny') NOT NULL,
  changed_by VARCHAR(32) NOT NULL,
  reason VARCHAR(500) NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (override_id),
  UNIQUE KEY ux_user_permission_override (user_id, permission_key),
  KEY idx_user_permission_overrides_permission (permission_key),
  CONSTRAINT fk_user_permission_overrides_user FOREIGN KEY (user_id) REFERENCES app_users (user_id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_user_permission_overrides_permission FOREIGN KEY (permission_key) REFERENCES access_permissions (permission_key) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_user_permission_overrides_changed_by FOREIGN KEY (changed_by) REFERENCES app_users (user_id) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS permission_audit_log (
  audit_id VARCHAR(40) NOT NULL,
  affected_user_id VARCHAR(32) NOT NULL,
  actor_user_id VARCHAR(32) NOT NULL,
  permission_key VARCHAR(128) NOT NULL,
  previous_effect ENUM('allow', 'deny') NULL,
  new_effect ENUM('allow', 'deny') NULL,
  reason VARCHAR(500) NULL,
  created_at DATETIME NOT NULL,
  PRIMARY KEY (audit_id),
  KEY idx_permission_audit_user_date (affected_user_id, created_at),
  KEY idx_permission_audit_permission (permission_key, created_at),
  CONSTRAINT fk_permission_audit_affected_user FOREIGN KEY (affected_user_id) REFERENCES app_users (user_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_permission_audit_actor FOREIGN KEY (actor_user_id) REFERENCES app_users (user_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_permission_audit_permission FOREIGN KEY (permission_key) REFERENCES access_permissions (permission_key) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO access_permissions
  (permission_key, module, section, action, display_name, description, active, created_at, updated_at)
VALUES
  ('dashboard.view', 'dashboard', NULL, 'view', 'View dashboard', 'View the main dashboard.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('vendors.view', 'vendors', NULL, 'view', 'View vendors', 'View vendor records subject to existing ownership rules.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('vendors.create', 'vendors', NULL, 'create', 'Create vendors', 'Create vendor records.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('vendors.edit', 'vendors', NULL, 'edit', 'Edit vendors', 'Edit vendor records subject to existing ownership rules.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('vendors.assign', 'vendors', NULL, 'assign', 'Assign vendors', 'Assign vendors to accountable users.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('deliveries.view', 'deliveries', NULL, 'view', 'View deliveries', 'View delivery records subject to existing scope rules.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('deliveries.create', 'deliveries', NULL, 'create', 'Create deliveries', 'Create delivery requests.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('deliveries.claim', 'deliveries', NULL, 'claim', 'Claim deliveries', 'Claim eligible delivery work.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('deliveries.assign', 'deliveries', NULL, 'assign', 'Assign deliveries', 'Assign delivery work.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('deliveries.reassign', 'deliveries', NULL, 'reassign', 'Reassign deliveries', 'Reassign delivery work.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('deliveries.deliver', 'deliveries', NULL, 'deliver', 'Complete deliveries', 'Mark eligible deliveries delivered.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('deliveries.cancel', 'deliveries', NULL, 'cancel', 'Cancel deliveries', 'Cancel eligible delivery requests.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('factory.view', 'factory', NULL, 'view', 'View factory', 'View factory operations.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('factory.production.create', 'factory', 'production', 'create', 'Record production', 'Record factory production.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('factory.movements.create', 'factory', 'movements', 'create', 'Record factory movements', 'Record factory stock movements.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('factory.records.reverse', 'factory', 'records', 'reverse', 'Reverse factory records', 'Reverse factory records where currently authorized.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('factory.expenses.manage', 'factory', 'expenses', 'manage', 'Manage factory expenses', 'Manage factory expenses and configuration.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('crm.view', 'crm', NULL, 'view', 'View CRM leads', 'View CRM leads subject to ownership rules.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('crm.create', 'crm', NULL, 'create', 'Create CRM leads', 'Create CRM leads.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('crm.edit', 'crm', NULL, 'edit', 'Edit CRM leads', 'Edit CRM leads subject to ownership rules.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('crm.follow_up.manage', 'crm', 'follow_up', 'manage', 'Manage CRM follow-ups', 'Manage CRM follow-up activity.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('crm.assign', 'crm', NULL, 'assign', 'Assign CRM leads', 'Assign or reassign CRM leads.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('outlets.view', 'outlets', NULL, 'view', 'View outlets', 'View outlet records.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('outlets.manage', 'outlets', NULL, 'manage', 'Manage outlets', 'Create and manage outlets.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('outlets.sales.record', 'outlets', 'sales', 'record', 'Record outlet sales', 'Record isolated outlet sales.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('outlets.stock.receive', 'outlets', 'stock', 'receive', 'Receive outlet stock', 'Record isolated outlet stock receipts.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('accountability.view', 'accountability', NULL, 'view', 'View accountability', 'View agent accountability.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('accountability.assign', 'accountability', NULL, 'assign', 'Assign accountability', 'Assign vendor accountability.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('accountability.collections.manage', 'accountability', 'collections', 'manage', 'Manage collections', 'Manage accountability collections.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('accountability.handovers.manage', 'accountability', 'handovers', 'manage', 'Manage handovers', 'Record and reconcile cash handovers.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('users.view', 'users', NULL, 'view', 'View users', 'View application users.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('users.create', 'users', NULL, 'create', 'Create users', 'Create application users.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('users.edit', 'users', NULL, 'edit', 'Edit users', 'Edit application users.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('users.assign_permissions', 'users', NULL, 'assign_permissions', 'Assign permissions', 'Manage future user-specific access restrictions.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('reports.view', 'reports', NULL, 'view', 'View reports', 'View reports and transactions.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('reports.export', 'reports', NULL, 'export', 'Export reports', 'Export report data.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('products.view', 'products', NULL, 'view', 'View products', 'View product catalog.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('products.manage', 'products', NULL, 'manage', 'Manage products', 'Manage product definitions.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('visits.view', 'visits', NULL, 'view', 'View visits', 'View visit records subject to existing scope rules.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('visits.create', 'visits', NULL, 'create', 'Record visits', 'Record visits subject to existing rules.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('visits.reverse', 'visits', NULL, 'reverse', 'Reverse visits', 'Reverse visits where currently authorized.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('forms.manage', 'forms', NULL, 'manage', 'Manage forms', 'Manage form definitions.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('forms.publish', 'forms', NULL, 'publish', 'Publish forms', 'Publish form versions.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
