'use client';

import { useMemo, useState, type ReactNode } from 'react';
import { useFactoryMovementsQuery } from '@/lib/hooks/queries';
import type { FactoryStockMovement } from '@/lib/types';

const labels: Record<string, string> = { production: 'Production', leaving_factory: 'Leaving Factory', returned_factory: 'Returned to Factory' };
const date = (value: string) => new Intl.DateTimeFormat('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(value));
const timestamp = (value: string) => new Intl.DateTimeFormat('en-GB', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value));
const duration = (item: FactoryStockMovement) => item.processing_duration_hours !== null && item.processing_duration_hours !== undefined && item.processing_duration_minutes !== null && item.processing_duration_minutes !== undefined ? `${item.processing_duration_hours}h ${String(item.processing_duration_minutes).padStart(2, '0')}m` : '-';

function ProductionDetail({ item, close }: { item: FactoryStockMovement; close: () => void }) {
  return <DetailShell title="Production detail" close={close}><div className="space-y-4 text-sm"><Detail label="Raw Material" value={item.raw_material || '-'} /><Detail label="Batch No." value={item.batch_reference || '-'} /><Detail label="Weight (kg)" value={item.input_quantity === null || item.input_quantity === undefined ? '-' : String(item.input_quantity)} /><Detail label="Temp °C" value={item.temperature_c === null || item.temperature_c === undefined ? '-' : String(item.temperature_c)} /><Detail label="Processing Duration" value={duration(item)} /><Detail label="Finished Product" value={item.product_name ?? item.product_id} /><Detail label="Output Quantity" value={String(item.quantity)} /><Detail label="Date" value={date(item.occurred_at)} /><Detail label="Recorded" value={timestamp(item.recorded_at)} /><Detail label="Actor" value={item.actor_name ?? item.actor_user_id} /></div></DetailShell>;
}

function MovementDetail({ items, close }: { items: FactoryStockMovement[]; close: () => void }) {
  const first = items[0];
  return <DetailShell title={`${labels[first.movement_type]} detail`} close={close}><div className="space-y-4 text-sm"><Detail label="Movement type" value={labels[first.movement_type]} /><Detail label="Date" value={date(first.occurred_at)} /><Detail label="Recorded" value={timestamp(first.recorded_at)} /><Detail label="Actor" value={first.actor_name ?? first.actor_user_id} /><div><p className="font-medium text-slate-500">Products</p><div className="mt-2 space-y-2">{items.map((item) => <div key={item.movement_id} className="flex justify-between gap-4 rounded-xl bg-slate-50 px-3 py-2"><span>{item.product_name ?? item.product_id}</span><span className="font-semibold">{item.quantity}</span></div>)}</div></div><Detail label="Reason / Comment" value={first.reason_comment || '-'} /><Detail label="Operation" value={first.operation_id} /></div></DetailShell>;
}

function DetailShell({ title, close, children }: { title: string; close: () => void; children: ReactNode }) {
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/40 p-3 sm:items-center"><div role="dialog" aria-modal="true" className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-3xl bg-white p-5 shadow-xl sm:p-6"><div className="flex items-center justify-between gap-4"><h3 className="text-xl font-semibold">{title}</h3><button type="button" onClick={close} className="rounded-full px-3 py-2 text-sm text-slate-500 hover:bg-slate-100">Close</button></div><div className="mt-5">{children}</div></div></div>;
}
function Detail({ label, value }: { label: string; value: string }) { return <div><p className="text-xs uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 text-slate-900">{value}</p></div>; }

export function FactoryHistory({ mode }: { mode: 'production' | 'movements' }) {
  const query = useFactoryMovementsQuery();
  const [selected, setSelected] = useState<FactoryStockMovement | FactoryStockMovement[] | null>(null);
  const records = useMemo(() => (query.data ?? []).filter((item) => mode === 'production' ? item.movement_type === 'production' : item.movement_type !== 'production'), [mode, query.data]);
  const events = useMemo(() => { const grouped = new Map<string, FactoryStockMovement[]>(); for (const item of records) { const key = item.event_id ?? item.operation_id; grouped.set(key, [...(grouped.get(key) ?? []), item]); } return Array.from(grouped.values()); }, [records]);
  return <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-soft sm:p-6"><div className="flex items-end justify-between gap-3"><div><p className="text-sm uppercase tracking-[0.22em] text-sidrah-500">History</p><h2 className="mt-2 text-xl font-semibold">{mode === 'production' ? 'Production history' : 'Movement history'}</h2></div><span className="text-xs text-slate-500">{mode === 'production' ? `${records.length} records` : `${events.length} events`}</span></div>
    {query.isLoading ? <p className="mt-5 text-sm text-slate-600">Loading history...</p> : query.isError ? <p role="alert" className="mt-5 rounded-2xl bg-rose-50 p-3 text-sm text-rose-900">Unable to load factory history. Please try again.</p> : events.length === 0 ? <p className="mt-5 text-sm text-slate-500">No {mode === 'production' ? 'production records' : 'movement events'} recorded yet.</p> : <div className="mt-5 space-y-3">{events.map((items) => { const first = items[0]; return <button type="button" key={first.event_id ?? first.operation_id} onClick={() => setSelected(mode === 'production' ? first : items)} className="block w-full rounded-2xl border border-slate-200 p-4 text-left transition hover:border-sidrah-300 hover:bg-sidrah-50 focus:outline-none focus:ring-2 focus:ring-sidrah-500">{mode === 'production' ? <><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-sidrah-600">Production</p><h3 className="mt-1 font-semibold">{first.product_name ?? first.product_id}</h3></div><span className="text-lg font-semibold text-sidrah-700">{first.quantity} units</span></div><p className="mt-3 text-sm text-slate-700">Batch {first.batch_reference || '-'} · {first.raw_material || '-'} · {first.input_quantity ?? '-'} kg</p><p className="mt-1 text-sm text-slate-600">{first.temperature_c ?? '-'}°C · {duration(first)}</p><p className="mt-3 text-xs text-slate-500">{first.actor_name ?? first.actor_user_id} · {date(first.occurred_at)}</p></> : <><div className="flex items-start justify-between gap-3"><p className="font-semibold">{labels[first.movement_type]}</p><span className="text-xs text-slate-500">{items.length} {items.length === 1 ? 'product' : 'products'}</span></div><div className="mt-3 space-y-1 text-sm text-slate-700">{items.map((item) => <p key={item.movement_id}>{item.product_name ?? item.product_id} · {item.quantity}</p>)}</div>{first.reason_comment ? <p className="mt-3 text-sm text-slate-600">{first.reason_comment}</p> : null}<p className="mt-3 text-xs text-slate-500">{first.actor_name ?? first.actor_user_id} · {date(first.occurred_at)}</p></>}</button>; })}</div>}
    {selected && (mode === 'production' ? <ProductionDetail item={selected as FactoryStockMovement} close={() => setSelected(null)} /> : <MovementDetail items={selected as FactoryStockMovement[]} close={() => setSelected(null)} />)}
  </section>;
}
