'use client';

import { useState, type FormEvent } from 'react';
import { useCreateFactoryContainerMovementMutation, useFactoryContainerInventoryQuery, useFactoryContainerMovementsQuery } from '@/lib/hooks/queries';
import type { FactoryContainerMovement, FactoryContainerMovementType, FactoryContainerType } from '@/lib/types';

const containerLabels: Record<FactoryContainerType, string> = { gallon: 'Gallons', bucket_5l: '5L Buckets', bucket_1kg: '1kg Buckets' };
const movementLabels: Record<FactoryContainerMovementType, string> = { received: 'Received', leaving_factory: 'Leaving Factory', returned_factory: 'Returned Empty Containers' };
const today = () => new Date().toISOString().slice(0, 10);
const date = (value: string) => new Intl.DateTimeFormat('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(value));
const timestamp = (value: string) => new Intl.DateTimeFormat('en-GB', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value));

function ContainerDetail({ item, close }: { item: FactoryContainerMovement; close: () => void }) {
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/40 p-3 sm:items-center"><div role="dialog" aria-modal="true" className="w-full max-w-lg rounded-3xl bg-white p-5 shadow-xl sm:p-6"><div className="flex items-center justify-between gap-4"><h3 className="text-xl font-semibold">Container movement detail</h3><button type="button" onClick={close} className="rounded-full px-3 py-2 text-sm text-slate-500 hover:bg-slate-100">Close</button></div><div className="mt-5 space-y-4 text-sm"><Detail label="Container Type" value={containerLabels[item.container_type]} /><Detail label="Movement Type" value={movementLabels[item.movement_type]} /><Detail label="Quantity" value={String(item.quantity)} /><Detail label="Reason / Comment" value={item.reason_comment || '-'} /><Detail label="Date" value={date(item.occurred_at)} /><Detail label="Recorded" value={timestamp(item.recorded_at)} /><Detail label="Actor" value={item.actor_name ?? item.actor_user_id} /><Detail label="Operation" value={item.operation_id} /></div></div></div>;
}
function Detail({ label, value }: { label: string; value: string }) { return <div><p className="text-xs uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 text-slate-900">{value}</p></div>; }

function ContainerMovementForm({ close }: { close: () => void }) {
  const mutation = useCreateFactoryContainerMovementMutation();
  const [containerType, setContainerType] = useState<FactoryContainerType>('gallon');
  const [movementType, setMovementType] = useState<FactoryContainerMovementType>('received');
  const [quantity, setQuantity] = useState(''); const [occurredAt, setOccurredAt] = useState(today()); const [reason, setReason] = useState('');
  const [message, setMessage] = useState<{ type: 'success' | 'error'; text: string } | null>(null);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setMessage(null);
    if (!occurredAt) return setMessage({ type: 'error', text: 'Date is required.' });
    if (!quantity || Number(quantity) <= 0) return setMessage({ type: 'error', text: 'Quantity must be greater than zero.' });
    try { await mutation.mutateAsync({ operation_id: crypto.randomUUID(), container_type: containerType, movement_type: movementType, quantity: Number(quantity), occurred_at: occurredAt, reason_comment: reason }); setMessage({ type: 'success', text: 'Container movement recorded.' }); setQuantity(''); setReason(''); }
    catch (error) { setMessage({ type: 'error', text: error instanceof Error ? error.message : 'Unable to save container movement.' }); }
  }
  return <div className="mt-4 rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="flex items-center justify-between"><h3 className="font-semibold">Record Container Movement</h3><button type="button" onClick={close} className="text-sm text-slate-500">Close</button></div><form onSubmit={submit} className="mt-4 space-y-4"><label className="block text-sm text-slate-700">Date<input type="date" value={occurredAt} onChange={(event) => setOccurredAt(event.target.value)} className="mt-2 w-full rounded-3xl border border-slate-200 bg-white px-4 py-3 outline-none" /></label><label className="block text-sm text-slate-700">Container Type<select value={containerType} onChange={(event) => setContainerType(event.target.value as FactoryContainerType)} className="mt-2 w-full rounded-3xl border border-slate-200 bg-white px-4 py-3 outline-none"><option value="gallon">Gallon</option><option value="bucket_5l">5L Bucket</option><option value="bucket_1kg">1kg Bucket</option></select></label><label className="block text-sm text-slate-700">Movement Type<select value={movementType} onChange={(event) => setMovementType(event.target.value as FactoryContainerMovementType)} className="mt-2 w-full rounded-3xl border border-slate-200 bg-white px-4 py-3 outline-none"><option value="received">Received</option><option value="leaving_factory">Leaving Factory</option><option value="returned_factory">Returned Empty Containers</option></select></label><label className="block text-sm text-slate-700">Quantity<input type="number" min="0.001" step="0.001" value={quantity} onChange={(event) => setQuantity(event.target.value)} className="mt-2 w-full rounded-3xl border border-slate-200 bg-white px-4 py-3 outline-none" /></label><label className="block text-sm text-slate-700">Reason / Comment<textarea value={reason} onChange={(event) => setReason(event.target.value)} rows={3} className="mt-2 w-full rounded-3xl border border-slate-200 bg-white px-4 py-3 outline-none" /></label>{message ? <p role={message.type === 'error' ? 'alert' : undefined} className={message.type === 'error' ? 'rounded-xl bg-rose-50 p-3 text-sm text-rose-900' : 'rounded-xl bg-emerald-50 p-3 text-sm text-emerald-900'}>{message.text}</p> : null}<button type="submit" disabled={mutation.isPending} className="w-full rounded-3xl bg-sidrah-500 px-4 py-3 text-sm font-semibold text-white disabled:opacity-50">{mutation.isPending ? 'Saving...' : 'Save Container Movement'}</button></form></div>;
}

export function FactoryContainerSection() {
  const inventory = useFactoryContainerInventoryQuery(); const movements = useFactoryContainerMovementsQuery(); const [showForm, setShowForm] = useState(false); const [selected, setSelected] = useState<FactoryContainerMovement | null>(null);
  return <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-soft sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm uppercase tracking-[0.22em] text-sidrah-500">Empty containers</p><h2 className="mt-2 text-xl font-semibold">Manual container inventory</h2><p className="mt-1 text-sm text-slate-600">Production and product movements do not change these quantities automatically.</p></div><button type="button" onClick={() => setShowForm((value) => !value)} className="rounded-3xl bg-sidrah-500 px-4 py-3 text-sm font-semibold text-white">+ Record Container Movement</button></div>{showForm ? <ContainerMovementForm close={() => setShowForm(false)} /> : null}{inventory.isLoading ? <p className="mt-5 text-sm text-slate-600">Loading container inventory...</p> : inventory.isError ? <p role="alert" className="mt-5 rounded-2xl bg-rose-50 p-3 text-sm text-rose-900">Unable to load container inventory. Please try again.</p> : <div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3">{(inventory.data ?? []).map((item) => <div key={item.container_type} className="rounded-2xl bg-slate-50 p-4"><p className="text-sm font-semibold">{containerLabels[item.container_type]}</p><p className="mt-2 text-2xl font-semibold text-sidrah-600">{item.current_quantity}</p><p className="text-xs text-slate-500">empty containers</p></div>)}</div>}<div className="mt-6 border-t border-slate-100 pt-5"><div className="flex items-center justify-between"><h3 className="font-semibold">Container history</h3><span className="text-xs text-slate-500">{movements.data?.length ?? 0} records</span></div>{movements.isLoading ? <p className="mt-4 text-sm text-slate-600">Loading container history...</p> : movements.isError ? <p role="alert" className="mt-4 rounded-2xl bg-rose-50 p-3 text-sm text-rose-900">Unable to load container history. Please try again.</p> : (movements.data ?? []).length === 0 ? <p className="mt-4 text-sm text-slate-500">No container movements recorded yet.</p> : <div className="mt-4 space-y-3">{(movements.data ?? []).map((item) => <button type="button" key={item.movement_id} onClick={() => setSelected(item)} className="block w-full rounded-2xl border border-slate-200 p-4 text-left hover:border-sidrah-300 hover:bg-sidrah-50 focus:outline-none focus:ring-2 focus:ring-sidrah-500"><div className="flex items-start justify-between gap-3"><p className="font-semibold">{movementLabels[item.movement_type]}</p><span className="text-lg font-semibold text-sidrah-700">{item.quantity}</span></div><p className="mt-1 text-sm text-slate-700">{containerLabels[item.container_type]}</p>{item.reason_comment ? <p className="mt-2 text-sm text-slate-600">{item.reason_comment}</p> : null}<p className="mt-3 text-xs text-slate-500">{item.actor_name ?? item.actor_user_id} · {date(item.occurred_at)}</p></button>)}</div>}</div>{selected ? <ContainerDetail item={selected} close={() => setSelected(null)} /> : null}</section>;
}
