'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import type { FactoryExpense, FactoryExpenseCategory, FactoryExpensePaymentMethod, FactoryExpenseSummary } from '@/lib/types';

const methods: FactoryExpensePaymentMethod[] = ['Cash', 'Bank Transfer', 'Mobile Money', 'Credit', 'Other'];
const money = (value: number) => `D${Number(value || 0).toLocaleString('en-GM', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const today = () => new Date().toISOString().slice(0, 10);
type Form = { expense_date: string; category_id: string; amount: string; description: string; quantity: string; unit: string; unit_price: string; paid_to: string; payment_method: FactoryExpensePaymentMethod; reference: string; notes: string };
const initialForm = (): Form => ({ expense_date: today(), category_id: '', amount: '', description: '', quantity: '', unit: '', unit_price: '', paid_to: '', payment_method: 'Cash', reference: '', notes: '' });

async function request<T>(url: string, options?: RequestInit): Promise<T> { const response = await fetch(url, { ...options, headers: { 'Content-Type': 'application/json', ...(options?.headers ?? {}) } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.message || 'Request failed.'); return body.data as T; }

export function FactoryExpenses() {
  const [categories, setCategories] = useState<FactoryExpenseCategory[]>([]); const [expenses, setExpenses] = useState<FactoryExpense[]>([]); const [summary, setSummary] = useState<FactoryExpenseSummary>({ today: 0, this_month: 0, total: 0, count: 0 });
  const [filters, setFilters] = useState({ from: '', to: '', category_id: '', payment_method: '', search: '' }); const [form, setForm] = useState<Form>(initialForm()); const [showForm, setShowForm] = useState(false); const [showCategories, setShowCategories] = useState(false); const [categoryName, setCategoryName] = useState(''); const [categoryGroup, setCategoryGroup] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const query = useMemo(() => { const params = new URLSearchParams(); Object.entries(filters).forEach(([key, value]) => { if (value) params.set(key, value); }); return params.toString(); }, [filters]);
  const loadCategories = useCallback(async () => { setCategories(await request<FactoryExpenseCategory[]>('/api/factory/expenses?view=categories')); }, []);
  const loadExpenses = useCallback(async () => { setLoading(true); try { const data = await request<{ expenses: FactoryExpense[]; summary: FactoryExpenseSummary }>(`/api/factory/expenses${query ? `?${query}` : ''}`); setExpenses(data.expenses); setSummary(data.summary); setError(''); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load expenses.'); } finally { setLoading(false); } }, [query]);
  useEffect(() => { loadCategories().catch(e => setError(e instanceof Error ? e.message : 'Unable to load categories.')); }, [loadCategories]); useEffect(() => { loadExpenses(); }, [loadExpenses]);
  function update<K extends keyof Form>(key: K, value: Form[K]) { setForm(current => ({ ...current, [key]: value })); }
  async function addExpense(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(''); try { await request('/api/factory/expenses', { method: 'POST', body: JSON.stringify({ ...form, amount: Number(form.amount), quantity: form.quantity ? Number(form.quantity) : undefined, unit_price: form.unit_price ? Number(form.unit_price) : undefined }) }); setForm(initialForm()); setShowForm(false); await loadExpenses(); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to save expense.'); } finally { setSaving(false); } }
  async function saveCategory(event: React.FormEvent) { event.preventDefault(); if (!categoryName.trim()) return; try { await request('/api/factory/expenses?view=categories', { method: 'POST', body: JSON.stringify({ name: categoryName, category_group: categoryGroup }) }); setCategoryName(''); setCategoryGroup(''); await loadCategories(); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to save category.'); } }
  async function toggleCategory(category: FactoryExpenseCategory) { try { await request(`/api/factory/expense-categories/${category.category_id}`, { method: 'PATCH', body: JSON.stringify({ is_active: !category.is_active }) }); await loadCategories(); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to update category.'); } }
  async function editCategory(category: FactoryExpenseCategory) { const name = window.prompt('Category name:', category.name); if (!name?.trim()) return; const group = window.prompt('Category group (optional):', category.category_group ?? ''); try { await request(`/api/factory/expense-categories/${category.category_id}`, { method: 'PATCH', body: JSON.stringify({ name: name.trim(), category_group: group?.trim() || null }) }); await loadCategories(); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to update category.'); } }
  async function voidExpense(expense: FactoryExpense) { const reason = window.prompt('Reason for voiding this expense:'); if (!reason?.trim()) return; try { await request(`/api/factory/expenses/${expense.expense_id}`, { method: 'PATCH', body: JSON.stringify({ reason }) }); await loadExpenses(); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to void expense.'); } }
  const activeCategories = categories.filter(category => category.is_active);
  return <section className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm text-slate-500">Admin-only expenditure control</p><p className="text-xs text-slate-500">Voided expenses remain in the audit history.</p></div><div className="flex gap-2"><button type="button" onClick={() => setShowCategories(value => !value)} className="rounded-2xl border px-4 py-3 font-semibold">Manage categories</button><button type="button" onClick={() => setShowForm(value => !value)} className="rounded-2xl bg-sidrah-500 px-4 py-3 font-semibold text-white">{showForm ? 'Close form' : 'Add expense'}</button></div></div>
    {error ? <p role="alert" className="rounded-2xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p> : null}
    {showCategories ? <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-soft"><h2 className="text-lg font-semibold">Expense categories</h2><form onSubmit={saveCategory} className="mt-4 grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><input aria-label="Category name" value={categoryName} onChange={e => setCategoryName(e.target.value)} placeholder="Category name" className="rounded-xl border p-3" /><input aria-label="Category group" value={categoryGroup} onChange={e => setCategoryGroup(e.target.value)} placeholder="Group (optional)" className="rounded-xl border p-3" /><button className="rounded-xl bg-slate-900 px-4 py-3 font-semibold text-white">Add</button></form><div className="mt-4 grid gap-2 sm:grid-cols-2">{categories.map(category => <div key={category.category_id} className="flex items-center justify-between gap-3 rounded-xl border p-3 text-sm"><span><b>{category.name}</b>{category.category_group ? <span className="ml-2 text-slate-500">{category.category_group}</span> : null}</span><span className="flex shrink-0 gap-3"><button type="button" onClick={() => editCategory(category)} className="font-semibold text-slate-700">Edit</button><button type="button" onClick={() => toggleCategory(category)} className="font-semibold text-sidrah-700">{category.is_active ? 'Deactivate' : 'Reactivate'}</button></span></div>)}</div></div> : null}
    {showForm ? <form onSubmit={addExpense} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-soft"><h2 className="text-lg font-semibold">Add expense</h2><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><label className="text-sm">Expense date<input required type="date" value={form.expense_date} onChange={e => update('expense_date', e.target.value)} className="mt-1 w-full rounded-xl border p-3" /></label><label className="text-sm">Category<select required value={form.category_id} onChange={e => update('category_id', e.target.value)} className="mt-1 w-full rounded-xl border p-3"><option value="">Select category</option>{activeCategories.map(c => <option key={c.category_id} value={c.category_id}>{c.name}</option>)}</select></label><label className="text-sm">Amount<input required min="0.01" step="0.01" type="number" value={form.amount} onChange={e => update('amount', e.target.value)} className="mt-1 w-full rounded-xl border p-3" /></label><label className="text-sm">Payment method<select value={form.payment_method} onChange={e => update('payment_method', e.target.value as FactoryExpensePaymentMethod)} className="mt-1 w-full rounded-xl border p-3">{methods.map(method => <option key={method}>{method}</option>)}</select></label><label className="text-sm">Description<input value={form.description} onChange={e => update('description', e.target.value)} className="mt-1 w-full rounded-xl border p-3" /></label><label className="text-sm">Paid To<input value={form.paid_to} onChange={e => update('paid_to', e.target.value)} className="mt-1 w-full rounded-xl border p-3" /></label><label className="text-sm">Quantity (optional)<input min="0.001" step="0.001" type="number" value={form.quantity} onChange={e => update('quantity', e.target.value)} className="mt-1 w-full rounded-xl border p-3" /></label><label className="text-sm">Unit<input value={form.unit} onChange={e => update('unit', e.target.value)} className="mt-1 w-full rounded-xl border p-3" /></label><label className="text-sm">Unit price<input min="0.01" step="0.01" type="number" value={form.unit_price} onChange={e => update('unit_price', e.target.value)} className="mt-1 w-full rounded-xl border p-3" /></label><label className="text-sm">Reference<input value={form.reference} onChange={e => update('reference', e.target.value)} className="mt-1 w-full rounded-xl border p-3" /></label><label className="text-sm sm:col-span-2">Notes<textarea value={form.notes} onChange={e => update('notes', e.target.value)} rows={2} className="mt-1 w-full rounded-xl border p-3" /></label></div><button disabled={saving} className="mt-4 rounded-xl bg-sidrah-500 px-4 py-3 font-semibold text-white disabled:opacity-50">{saving ? 'Saving...' : 'Save expense'}</button></form> : null}
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Summary label="Today's Expenditure" value={money(summary.today)} /><Summary label="This Month's Expenditure" value={money(summary.this_month)} /><Summary label="Filtered Expenditure" value={money(summary.total)} /><Summary label="Number of Expenses" value={String(summary.count)} /></div>
    <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-soft"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><label className="text-sm">From<input type="date" value={filters.from} onChange={e => setFilters(f => ({ ...f, from: e.target.value }))} className="mt-1 w-full rounded-xl border p-3" /></label><label className="text-sm">To<input type="date" value={filters.to} onChange={e => setFilters(f => ({ ...f, to: e.target.value }))} className="mt-1 w-full rounded-xl border p-3" /></label><label className="text-sm">Category<select value={filters.category_id} onChange={e => setFilters(f => ({ ...f, category_id: e.target.value }))} className="mt-1 w-full rounded-xl border p-3"><option value="">All categories</option>{categories.map(c => <option key={c.category_id} value={c.category_id}>{c.name}</option>)}</select></label><label className="text-sm">Payment method<select value={filters.payment_method} onChange={e => setFilters(f => ({ ...f, payment_method: e.target.value }))} className="mt-1 w-full rounded-xl border p-3"><option value="">All methods</option>{methods.map(method => <option key={method}>{method}</option>)}</select></label><label className="text-sm">Search description/payee<input value={filters.search} onChange={e => setFilters(f => ({ ...f, search: e.target.value }))} className="mt-1 w-full rounded-xl border p-3" /></label></div></div>
    <div className="overflow-x-auto rounded-3xl border border-slate-200 bg-white shadow-soft">{loading ? <p className="p-5 text-sm text-slate-600">Loading expenses...</p> : expenses.length === 0 ? <p className="p-5 text-sm text-slate-600">No expenses match the selected filters.</p> : <table className="min-w-full text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{['Date','Category','Description','Amount','Paid To','Payment Method','Recorded By','Status',''].map(label => <th key={label} className="px-4 py-3">{label}</th>)}</tr></thead><tbody>{expenses.map(expense => <tr key={expense.expense_id} className="border-b last:border-0"><td className="px-4 py-3 whitespace-nowrap">{expense.expense_date}</td><td className="px-4 py-3">{expense.category_name}</td><td className="px-4 py-3">{expense.description || '-'}</td><td className="px-4 py-3 font-semibold">{money(expense.amount)}</td><td className="px-4 py-3">{expense.paid_to || '-'}</td><td className="px-4 py-3">{expense.payment_method}</td><td className="px-4 py-3">{expense.recorded_by_name || 'Unknown'}</td><td className="px-4 py-3"><span className={expense.status === 'voided' ? 'text-rose-700' : 'text-emerald-700'}>{expense.status}</span></td><td className="px-4 py-3">{expense.status === 'active' ? <button type="button" onClick={() => voidExpense(expense)} className="font-semibold text-rose-700">Void</button> : expense.void_reason ? <span className="text-xs text-slate-500" title={expense.void_reason}>Reason</span> : null}</td></tr>)}</tbody></table>}</div>
  </section>;
}
function Summary({ label, value }: { label: string; value: string }) { return <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-soft"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold text-slate-900">{value}</p></div>; }
