'use client';
import Link from 'next/link';
import { useState } from 'react';
import { useCreateOutletMutation, useOutletsQuery } from '@/lib/hooks/outletQueries';

export function OutletList() {
  const query = useOutletsQuery(); const create = useCreateOutletMutation(); const [form, setForm] = useState({ name: '', location: '', responsible_person: '', phone: '', description: '' });
  const submit = (event: React.FormEvent) => { event.preventDefault(); create.mutate(form, { onSuccess: () => setForm({ name: '', location: '', responsible_person: '', phone: '', description: '' }) }); };
  return <div className="space-y-6">
    <form onSubmit={submit} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-soft"><h2 className="text-lg font-semibold">Create Outlet</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><input required placeholder="Outlet name" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} className="rounded-2xl border p-3" /><input placeholder="Location / address" value={form.location} onChange={e => setForm({ ...form, location: e.target.value })} className="rounded-2xl border p-3" /><input placeholder="Responsible person" value={form.responsible_person} onChange={e => setForm({ ...form, responsible_person: e.target.value })} className="rounded-2xl border p-3" /><input placeholder="Phone" value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })} className="rounded-2xl border p-3" /><textarea placeholder="Description / notes" value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} className="rounded-2xl border p-3 sm:col-span-2" /></div><button disabled={create.isPending} className="mt-4 rounded-2xl bg-sidrah-500 px-4 py-3 font-semibold text-white">{create.isPending ? 'Saving…' : 'Create Outlet'}</button>{create.isError && <p className="mt-2 text-sm text-rose-600">{create.error.message}</p>}</form>
    {query.isLoading ? <p>Loading outlets…</p> : query.isError ? <p className="text-rose-600">Unable to load outlets.</p> : <div className="grid gap-4 md:grid-cols-2">{(query.data ?? []).map(outlet => <Link key={outlet.outlet_id} href={`/outlets/${outlet.outlet_id}`} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-soft transition hover:border-sidrah-300"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold text-slate-900">{outlet.name}</h3><p className="mt-1 text-sm text-slate-600">{outlet.location || 'Location not specified'}</p><p className="mt-1 text-sm text-slate-600">{outlet.responsible_person || 'No responsible person'}</p><p className="mt-3 text-sm text-slate-500">Sales: GMD {Number(outlet.total_sales ?? 0).toLocaleString()}</p></div><span className={outlet.active ? 'text-sm font-semibold text-emerald-700' : 'text-sm font-semibold text-slate-500'}>{outlet.active ? 'Active' : 'Inactive'}</span></div></Link>)}</div>}
  </div>;
}
