import { randomUUID } from 'crypto';
import { getPool, transaction } from '@/lib/db';
import type { FactoryExpense, FactoryExpenseCategory, FactoryExpensePaymentMethod, FactoryExpenseSummary } from '@/lib/types';
import { FactoryExpenseRepository, type ExpenseFilters } from '@/repositories/FactoryExpenseRepository';

export class FactoryExpenseError extends Error { public readonly status: number; constructor(status: number, message: string) { super(message); this.status = status; } }
const methods: readonly FactoryExpensePaymentMethod[] = ['Cash', 'Bank Transfer', 'Mobile Money', 'Credit', 'Other'];
const id = () => `FEX_${randomUUID().replace(/-/g, '').slice(0, 20)}`;
function text(value: unknown, label: string, required = false): string | null { if (value == null || String(value).trim() === '') { if (required) throw new FactoryExpenseError(400, `${label} is required.`); return null; } return String(value).trim(); }
function date(value: unknown): string { const result = text(value, 'Expense date', true) as string; if (!/^\d{4}-\d{2}-\d{2}$/.test(result)) throw new FactoryExpenseError(400, 'Expense date must be YYYY-MM-DD.'); const parsed = new Date(`${result}T00:00:00Z`); if (Number.isNaN(parsed.getTime()) || parsed.toISOString().slice(0, 10) !== result) throw new FactoryExpenseError(400, 'Expense date is invalid.'); return result; }
function positive(value: unknown, label: string, required: boolean): number | null { if (value == null || value === '') { if (required) throw new FactoryExpenseError(400, `${label} is required.`); return null; } const number = Number(value); if (!Number.isFinite(number) || number <= 0) throw new FactoryExpenseError(400, `${label} must be greater than zero.`); return number; }
function filters(params: URLSearchParams): ExpenseFilters { return { from: params.get('from') || undefined, to: params.get('to') || undefined, categoryId: params.get('category_id') || undefined, paymentMethod: (params.get('payment_method') || undefined) as FactoryExpensePaymentMethod | undefined, search: params.get('search') || undefined }; }

export async function listCategories(includeInactive = true): Promise<FactoryExpenseCategory[]> { return new FactoryExpenseRepository(getPool()).listCategories(includeInactive); }
export async function addCategory(payload: unknown, actor: string): Promise<FactoryExpenseCategory> { const value = (payload ?? {}) as Record<string, unknown>; const name = text(value.name, 'Category name', true) as string; if (name.length > 128) throw new FactoryExpenseError(400, 'Category name is too long.'); return new FactoryExpenseRepository(getPool()).createCategory(id(), name, text(value.category_group, 'Category group'), actor); }
export async function editCategory(categoryId: string, payload: unknown): Promise<FactoryExpenseCategory> { const value = (payload ?? {}) as Record<string, unknown>; const updates: { name?: string; category_group?: string | null; is_active?: boolean } = {}; if (value.name !== undefined) updates.name = text(value.name, 'Category name', true) as string; if (value.category_group !== undefined) updates.category_group = text(value.category_group, 'Category group'); if (value.is_active !== undefined) { if (typeof value.is_active !== 'boolean') throw new FactoryExpenseError(400, 'is_active must be boolean.'); updates.is_active = value.is_active; } return new FactoryExpenseRepository(getPool()).updateCategory(categoryId, updates); }
export async function getExpenses(params: URLSearchParams): Promise<{ expenses: FactoryExpense[]; summary: FactoryExpenseSummary }> { const repo = new FactoryExpenseRepository(getPool()); const current = filters(params); return { expenses: await repo.listExpenses(current), summary: await repo.summary(current) }; }
export async function createExpense(payload: unknown, actor: string): Promise<FactoryExpense> {
  const value = (payload ?? {}) as Record<string, unknown>; const expenseDate = date(value.expense_date); const categoryId = text(value.category_id, 'Category', true) as string; const amount = positive(value.amount, 'Amount', true) as number; const quantity = positive(value.quantity, 'Quantity', false); const unitPrice = positive(value.unit_price, 'Unit price', false); const paymentMethod = text(value.payment_method, 'Payment method', true) as string;
  if (!methods.includes(paymentMethod as FactoryExpensePaymentMethod)) throw new FactoryExpenseError(400, 'Payment method is invalid.');
  const payloadData = { expense_id: id(), expense_date: expenseDate, category_id: categoryId, description: text(value.description, 'Description'), amount, quantity, unit: text(value.unit, 'Unit'), unit_price: unitPrice, paid_to: text(value.paid_to, 'Paid to'), payment_method: paymentMethod, reference: text(value.reference, 'Reference'), notes: text(value.notes, 'Notes'), recorded_by: actor };
  return transaction(async (connection) => { const repo = new FactoryExpenseRepository(connection); const categories = await repo.listCategories(false); if (!categories.some((category) => category.category_id === categoryId)) throw new FactoryExpenseError(400, 'Selected category is not active.'); const expense = await repo.createExpense(payloadData); await connection.execute(`INSERT INTO transaction_journal (transaction_id,timestamp,endpoint,stage,status,payload,completed,actor,error_message,duration_ms) VALUES (?,?,?,?,?,?,?,?,?,?)`, [expense.expense_id, new Date().toISOString().slice(0, 19).replace('T', ' '), '/factory/expenses', 'create', 'success', JSON.stringify({ expense_id: expense.expense_id, amount, category_id: categoryId }), true, actor, null, 0]); return expense; });
}
export async function voidExpense(expenseId: string, reason: unknown, actor: string): Promise<FactoryExpense> { const normalized = text(reason, 'Void reason', true) as string; if (normalized.length > 1000) throw new FactoryExpenseError(400, 'Void reason is too long.'); return transaction(async (connection) => { const repo = new FactoryExpenseRepository(connection); const expense = await repo.voidExpense(expenseId, actor, normalized); await connection.execute(`INSERT INTO transaction_journal (transaction_id,timestamp,endpoint,stage,status,payload,completed,actor,error_message,duration_ms) VALUES (?,?,?,?,?,?,?,?,?,?)`, [expenseId, new Date().toISOString().slice(0, 19).replace('T', ' '), '/factory/expenses', 'void', 'success', JSON.stringify({ expense_id: expenseId, reason: normalized }), true, actor, null, 0]); return expense; }); }
export { filters as parseExpenseFilters };
