'use client';
import { useEffect, useState } from 'react';
import { useCreateCrmLeadMutation, useUpdateCrmLeadMutation } from '@/lib/hooks/crmLeadQueries';
import type { CrmLead, CrmLeadStatus } from '@/lib/types/crm';
const statuses: Array<[CrmLeadStatus, string]> = [['new', 'New'], ['follow_up_required', 'Follow-up Required'], ['converted', 'Converted'], ['not_interested', 'Not Interested'], ['lost', 'Lost']];
export function LeadForm({ lead, onDone }: { lead?: CrmLead; onDone: (lead: CrmLead) => void }) {
  const mutation = lead ? useUpdateCrmLeadMutation() : useCreateCrmLeadMutation();
  const [form, setForm] = useState<Record<string, string>>({ lead_name: lead?.lead_name ?? '', phone: lead?.phone ?? '', location: lead?.location ?? '', business_type: lead?.business_type ?? '', lead_source: lead?.lead_source ?? '', captured_at: lead?.captured_at ?? new Date().toISOString().slice(0, 10), status: lead?.status ?? 'new', notes: lead?.notes ?? '', next_follow_up_date: lead?.next_follow_up_date ?? '' });
  const [error, setError] = useState('');
  useEffect(() => { if (lead) setForm(current => ({ ...current, lead_id: lead.lead_id, lead_name: lead.lead_name, captured_at: lead.captured_at, status: lead.status, ...current, next_follow_up_date: lead.next_follow_up_date ?? '', phone: lead.phone ?? '', location: lead.location ?? '', business_type: lead.business_type ?? '', lead_source: lead.lead_source ?? '', notes: lead.notes ?? '' })); }, [lead]);
  const set = (key: string, value: string) => setForm(current => ({ ...current, [key]: value }));
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(''); try { const result = lead ? await (mutation as any).mutateAsync({ leadId: lead.lead_id, payload: form }) : await (mutation as any).mutateAsync(form); onDone(result); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to save lead.'); } }
  return <form onSubmit={submit} className="space-y-4 rounded-3xl border border-slate-200 bg-white p-5 shadow-soft"><h2 className="text-xl font-semibold">{lead ? 'Edit lead' : 'Create lead'}</h2>{error ? <p role="alert" className="rounded-2xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p> : null}<label className="block text-sm">Lead name<input required value={form.lead_name} onChange={e => set('lead_name', e.target.value)} className="mt-1 w-full rounded-2xl border p-3" /></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm">Phone<input value={form.phone} onChange={e => set('phone', e.target.value)} className="mt-1 w-full rounded-2xl border p-3" /></label><label className="block text-sm">Location/address<input value={form.location} onChange={e => set('location', e.target.value)} className="mt-1 w-full rounded-2xl border p-3" /></label><label className="block text-sm">Business type<input value={form.business_type} onChange={e => set('business_type', e.target.value)} className="mt-1 w-full rounded-2xl border p-3" /></label><label className="block text-sm">Lead source<input value={form.lead_source} onChange={e => set('lead_source', e.target.value)} className="mt-1 w-full rounded-2xl border p-3" /></label><label className="block text-sm">Capture date<input required type="date" value={form.captured_at} onChange={e => set('captured_at', e.target.value)} className="mt-1 w-full rounded-2xl border p-3" /></label><label className="block text-sm">Status<select value={form.status} onChange={e => set('status', e.target.value)} className="mt-1 w-full rounded-2xl border p-3">{statuses.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="block text-sm">Next follow-up date<input type="date" value={form.next_follow_up_date} onChange={e => set('next_follow_up_date', e.target.value)} className="mt-1 w-full rounded-2xl border p-3" /></label></div><label className="block text-sm">Notes<textarea rows={4} value={form.notes} onChange={e => set('notes', e.target.value)} className="mt-1 w-full rounded-2xl border p-3" /></label><button disabled={mutation.isPending} className="rounded-2xl bg-sidrah-500 px-5 py-3 font-semibold text-white">{mutation.isPending ? 'Saving...' : 'Save lead'}</button></form>;
}
